 export interface redWhiteCardInterface {
     es:{
         card1:{
        URLpath?:string,
        spanText?:string,
        date?:string,
        h5Text?:string
        paragraphText?:string,
     },
     card2:{
        URLpath?:string,
        spanText?:string,
        date?:string,
        h5Text?:string
        paragraphText?:string,
     },
     card3:{
        URLpath?:string,
        spanText?:string,
        date?:string,
        h5Text?:string
        paragraphText?:string,
     },
     card4:{
        URLpath?:string,
        spanText?:string,
        date?:string,
        h5Text?:string
        paragraphText?:string,
     },
     card5:{
        URLpath?:string,
        spanText?:string,
        date?:string,
        h5Text?:string
        paragraphText?:string,
     },
     card6:{
        URLpath?:string,
        spanText?:string,
        date?:string,
        h5Text?:string
        paragraphText?:string,
     },
     }
}
